### ISSUE TITLE
Chapter renames broke your Medium article

### ISSUE THREAD

**Issue by ghost** [CrowdsourcingKC/crowdsourcingshortcut#1]
When you renamed the chapters, you broke the link to one of them in your blog post here: https://medium.com/the-documentarian-planetarium/github-pages-for-the-budding-technical-writer-a-review-38e3a22da82a

Not exactly a bug here, but the best way I could think of, to point out the problem to you. (The fact that I couldn't just give you a PR with the corrected link kind of shows the point of your article...)

**Comment by CrowdsourcingKC** [comment]
Fixed! Thank you. Good point : )
